# Generated by Django 3.2.5 on 2021-07-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210725_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='team',
            new_name='status',
        ),
    ]
